/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * Innere Komponente — simuliert u-data-table-header.
     * Empfängt den Relay-Slot [slot="action"] von repro-outer.
     */
    interface ReproInner {
    }
    /**
     * Äußere Komponente — simuliert u-data-table.
     * Hat einen Relay-Slot: <slot name="action" slot="action" />
     * der den Content an repro-inner weiterreicht.
     */
    interface ReproOuter {
    }
    /**
     * Äußerste Ebene — simuliert einen App-Level Container.
     * Hat einen Relay-Slot der an repro-outer weiterreicht.
     */
    interface ReproWrapper {
    }
}
declare global {
    /**
     * Innere Komponente — simuliert u-data-table-header.
     * Empfängt den Relay-Slot [slot="action"] von repro-outer.
     */
    interface HTMLReproInnerElement extends Components.ReproInner, HTMLStencilElement {
    }
    var HTMLReproInnerElement: {
        prototype: HTMLReproInnerElement;
        new (): HTMLReproInnerElement;
    };
    /**
     * Äußere Komponente — simuliert u-data-table.
     * Hat einen Relay-Slot: <slot name="action" slot="action" />
     * der den Content an repro-inner weiterreicht.
     */
    interface HTMLReproOuterElement extends Components.ReproOuter, HTMLStencilElement {
    }
    var HTMLReproOuterElement: {
        prototype: HTMLReproOuterElement;
        new (): HTMLReproOuterElement;
    };
    /**
     * Äußerste Ebene — simuliert einen App-Level Container.
     * Hat einen Relay-Slot der an repro-outer weiterreicht.
     */
    interface HTMLReproWrapperElement extends Components.ReproWrapper, HTMLStencilElement {
    }
    var HTMLReproWrapperElement: {
        prototype: HTMLReproWrapperElement;
        new (): HTMLReproWrapperElement;
    };
    interface HTMLElementTagNameMap {
        "repro-inner": HTMLReproInnerElement;
        "repro-outer": HTMLReproOuterElement;
        "repro-wrapper": HTMLReproWrapperElement;
    }
}
declare namespace LocalJSX {
    /**
     * Innere Komponente — simuliert u-data-table-header.
     * Empfängt den Relay-Slot [slot="action"] von repro-outer.
     */
    interface ReproInner {
    }
    /**
     * Äußere Komponente — simuliert u-data-table.
     * Hat einen Relay-Slot: <slot name="action" slot="action" />
     * der den Content an repro-inner weiterreicht.
     */
    interface ReproOuter {
    }
    /**
     * Äußerste Ebene — simuliert einen App-Level Container.
     * Hat einen Relay-Slot der an repro-outer weiterreicht.
     */
    interface ReproWrapper {
    }
    interface IntrinsicElements {
        "repro-inner": ReproInner;
        "repro-outer": ReproOuter;
        "repro-wrapper": ReproWrapper;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Innere Komponente — simuliert u-data-table-header.
             * Empfängt den Relay-Slot [slot="action"] von repro-outer.
             */
            "repro-inner": LocalJSX.IntrinsicElements["repro-inner"] & JSXBase.HTMLAttributes<HTMLReproInnerElement>;
            /**
             * Äußere Komponente — simuliert u-data-table.
             * Hat einen Relay-Slot: <slot name="action" slot="action" />
             * der den Content an repro-inner weiterreicht.
             */
            "repro-outer": LocalJSX.IntrinsicElements["repro-outer"] & JSXBase.HTMLAttributes<HTMLReproOuterElement>;
            /**
             * Äußerste Ebene — simuliert einen App-Level Container.
             * Hat einen Relay-Slot der an repro-outer weiterreicht.
             */
            "repro-wrapper": LocalJSX.IntrinsicElements["repro-wrapper"] & JSXBase.HTMLAttributes<HTMLReproWrapperElement>;
        }
    }
}
